# Generated by Django 3.1.2 on 2020-10-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bidlisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidprice',
        ),
    ]
