# Generated by Django 3.1.2 on 2020-10-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_bid_bidprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidlisting',
            name='bidprice',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
