# Generated by Django 3.1.2 on 2020-10-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201029_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='listings',
            field=models.ManyToManyField(to='auctions.BidListing'),
        ),
    ]
