# Generated by Django 3.1.2 on 2020-10-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201030_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidlisting',
            name='bidprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
