# Generated by Django 3.1.2 on 2020-10-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201030_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidlisting',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
