# Generated by Django 3.1.2 on 2020-10-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bidlisting_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidprice',
        ),
    ]
