# Generated by Django 3.1.2 on 2020-11-06 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201101_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.user'),
        ),
    ]
