# Generated by Django 3.1.2 on 2020-11-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_comment_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
