# Generated by Django 3.1.2 on 2020-11-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_bid_bidprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BidListing',
        ),
    ]
