# Generated by Django 3.1.2 on 2020-11-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_delete_bidlisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidden',
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSE', 'Close')], default='ACTIVE', max_length=6),
        ),
    ]
