# Generated by Django 3.1.2 on 2020-11-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auto_20201111_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidstatus',
            field=models.CharField(choices=[('WON', 'Won'), ('LOST', 'Lost'), ('PENDING', 'Pending')], default='PENDING', max_length=8),
        ),
    ]
