# Generated by Django 3.1.2 on 2020-11-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_bid_bidstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
