# Generated by Django 3.1.2 on 2020-11-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_bid_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('E', 'Electronis'), ('F', 'Furniture'), ('B', 'Books')], max_length=1, null=True),
        ),
    ]
