# Generated by Django 3.1.2 on 2020-11-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('E', 'Electronics'), ('F', 'Furniture'), ('B', 'Books')], max_length=1, null=True),
        ),
    ]
