# Generated by Django 3.1.2 on 2020-12-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0041_auto_20201203_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_pics',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
