# Generated by Django 3.1.2 on 2020-12-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0042_auto_20201203_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_pics',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
